export const Constants = {
  STATUS_SUCCESS: 200,
  STATUS_CREATED: 201,
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORIZED: 401,
  STATUS_FORBIDDEN: 403,
  STATUS_NOT_FOUND: 404,
  STATUS_LOCKED: 423,
  STATUS_INTERNAL_ERROR: 500,
  
  // Response statuses
  STATUS: 'error',
  STATUS_FAILURE: 'failure'
}