service: tenda-app-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
    DB_HOST: ${env:DB_HOST, 'localhost'}
    DB_PORT: ${env:DB_PORT, '5432'}
    DB_NAME: ${env:DB_NAME, 'gaming_key_platform'}
    DB_USER: ${env:DB_USER, 'postgres'}
    DB_PASSWORD: ${env:DB_PASSWORD, ''}
    JWT_SECRET: ${env:JWT_SECRET, 'your-super-secret-jwt-key'}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN, '7d'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds:*
          Resource: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  internal:
    handler: src/functions/internal/db.handler
    events:
      - http:
          path: /internal
          method: post
          cors: true
  login:
    handler: src/functions/auth/login.handler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true
  getGames:
    handler: src/functions/services/getGames.handler
    events:
      - http:
          path: /games
          method: get
          cors: true

  getPricing:
    handler: src/functions/services/getPricing.handler
    events:
      - http:
          path: /games/{gameId}/pricing
          method: get
          cors: true
  register:
    handler: src/functions/auth/register.handler
    events:
      - http:
          path: /auth/register
          method: post
          cors: true

  getPendingLoginRequests:
    handler: src/functions/auth/getPendingLoginRequests.handler
    events:
      - http:
          path: /dev/auth/login-requests/pending
          method: get
          cors: true

  # Users
  getUsers:
    handler: src/functions/users/getUsers.handler
    events:
      - http:
          path: /users
          method: get
          cors: true

  createUser:
    handler: src/functions/users/createUser.handler
    events:
      - http:
          path: /users
          method: post
          cors: true

  updateUser:
    handler: src/functions/users/updateUser.handler
    events:
      - http:
          path: /users/{userId}/update
          method: put
          cors: true

  # Analytics
  getAnalytics:
    handler: src/functions/analytics/getAnalytics.handler
    events:
      - http:
          path: /analytics/overview
          method: get
          cors: true
      - http:
          path: /analytics/usage
          method: get
          cors: true
      - http:
          path: /analytics/games
          method: get
          cors: true
      - http:
          path: /analytics/activity
          method: get
          cors: true

  # Settings
  getSettings:
    handler: src/functions/settings/getSettings.handler
    events:
      - http:
          path: /settings/profile
          method: get
          cors: true
      - http:
          path: /settings/profile
          method: put
          cors: true
      - http:
          path: /settings/password
          method: put
          cors: true
      - http:
          path: /settings/organization
          method: get
          cors: true
      - http:
          path: /settings/organization
          method: put
          cors: true
      - http:
          path: /settings/notifications
          method: get
          cors: true
      - http:
          path: /settings/notifications
          method: put
          cors: true

  # Organizations
  getOrganization:
    handler: src/functions/organizations/getOrganization.handler
    events:
      - http:
          path: /organizations/profile
          method: get
          cors: true

  updateOrganization:
    handler: src/functions/organizations/updateOrganization.handler
    events:
      - http:
          path: /organizations/profile
          method: put
          cors: true

  # API Keys
  generateKeys:
    handler: src/functions/keys/generateKeys.handler
    events:
      - http:
          path: /key-generation/generate
          method: post
          cors: true

  getUserKeys:
    handler: src/functions/keys/getUserKeys.handler
    events:
      - http:
          path: /my-keys
          method: get
          cors: true

custom:
  serverless-offline:
    httpPort: 3001
  dotenv:
    path: .env
